### ISSUE TITLE
12 TB as threshold for selecting Synapse Dedicated Pools vs Azure SQL DB Hyperscale

### ISSUE THREAD

**Issue by tonio-lora** [albero-azure/albero#123]
Hi Team,
First, excellent job putting this together. 
Where can I find more information about some of the numbers used on the decision points? For example, why is 12 TB the threshold to select Azure Synapse Dedicated pools over Azure SQL DB Hyperscale?
Thanks,

**Comment by misterious-mister-x** [comment]
Hi Tonio
This is a good question. In reality there is no official documentation on it. It can be considered more as an indicative number after which it makes sense to lean towards Synapse. Reason being that there are very few pure OLTP databases which are holding that amount of data. As DB grows, the pressure start mainly coming from read side where Synapse Dedicated has better chances to fulfill the requirements due to the MPP & Scale-Out architecture (of course there is expense for it). 

Also keep in mind that this whole DT is for your consideration and your knowledge of the workload should be applied on top of it ;) we do not want to repeat the faith of Enterprise Apps patterns here ;)

We are working on collecting some feedback from benchmarks / PoCs / Projects to check these points of view and are planning to start adding this in the nearest future. If you want to share the feedback from your project / PoC - I can share the form via the repo.

Hope this answers your question.

P.S. Sorry for slight delay in my replies.

**Comment by misterious-mister-x** [comment]
Since there was no further communication I am closing this issue.
